#!/usr/bin/env python
import logging
from app import app

if not app.config['DEBUG']:
    logging.basicConfig(filename='app.log', level=logging.INFO)

app.run(host=app.config['HOST'],
        port=app.config['PORT'],
        debug=app.config['DEBUG'])
