#!/usr/bin/env python
import logging
from app import app

if not app.config['DEBUG']:
    logging.basicConfig(filename=app.config['LOG_PATH'],
                        level=logging.INFO)

app.run(host=app.config['HOST'],
        port=app.config['PORT'],
        debug=app.config['DEBUG'],
        threaded=app.config['THREADING'])
